In [1]:
import numpy as np

In [2]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
array = np.full(10, 0.0)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
array = np.repeat(0.0, 10) 
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
array = np.repeat([0.0, 1.0], 5)
array

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [7]:
array = np.repeat([0.0, 1.0], [2, 3])
array

array([0., 0., 1., 1., 1.])

In [8]:
el = array[1]
print(el)

0.0


In [9]:
array[[4, 2, 0]]

array([1., 1., 0.])

In [10]:
array[1] = 1
print(array)

[0. 1. 1. 1. 1.]


In [11]:
elements = [1, 2, 3, 4]
array = np.array(elements)
array

array([1, 2, 3, 4])

In [12]:
zeros = np.zeros(10, dtype=np.uint8)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [13]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


In [14]:
thresholds = np.linspace(0, 1, 11)
thresholds

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
zeros[0] = 300
zeros

C:\Users\wangj\AppData\Local\Temp\ipykernel_5020\1640675828.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  zeros[0] = 300


array([44,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=uint8)

In [16]:
zeros[0] = 300
print(zeros[0])

44


C:\Users\wangj\AppData\Local\Temp\ipykernel_5020\2020449431.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  zeros[0] = 300


In [17]:
300 % 256


44

In [18]:
zeros = np.zeros((5, 2), dtype=np.float32)
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [19]:
print(zeros.shape)

(5, 2)


In [20]:
numbers = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

numbers = np.array(numbers)

In [21]:
print(numbers[0, 1])


2


In [22]:
numbers[0, 1] = 10

In [23]:
numbers

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [24]:
numbers[0]

array([ 1, 10,  3])

In [25]:
numbers[:, 1]

array([10,  5,  8])

In [26]:
numbers[1] = [1, 1, 1]

In [27]:
numbers

array([[ 1, 10,  3],
       [ 1,  1,  1],
       [ 7,  8,  9]])

In [28]:
numbers[:, 2] = [9, 9, 9]

In [29]:
numbers

array([[ 1, 10,  9],
       [ 1,  1,  9],
       [ 7,  8,  9]])

In [30]:
np.random.rand(5, 2)

array([[0.00768053, 0.73196896],
       [0.0820253 , 0.12025354],
       [0.33556888, 0.74300204],
       [0.40233554, 0.74464984],
       [0.32280383, 0.69056123]])

In [31]:
np.random.seed(2)
arr = np.random.rand(5, 2)
arr

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [32]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [33]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [34]:
rng = np.arange(5)
rng

array([0, 1, 2, 3, 4])

In [35]:
rng * 2

array([0, 2, 4, 6, 8])

In [36]:
(rng - 1) * 3 / 2 + 1

array([-0.5,  1. ,  2.5,  4. ,  5.5])

In [37]:
np.random.seed(2)
noise = 0.01 * np.random.rand(5)
noise

array([0.00435995, 0.00025926, 0.00549662, 0.00435322, 0.00420368])

In [38]:
numbers = np.arange(5)
numbers

array([0, 1, 2, 3, 4])

In [39]:
result = numbers + noise
result

array([0.00435995, 1.00025926, 2.00549662, 3.00435322, 4.00420368])

In [40]:
result.round(4)

array([0.0044, 1.0003, 2.0055, 3.0044, 4.0042])

In [41]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [42]:
square = pred * pred
square

array([0.1936, 0.0009, 0.3025])

In [43]:
square = pred ** 2
square

array([0.1936, 0.0009, 0.3025])

In [44]:
np.exp(pred)

array([1.55270722, 1.03045453, 1.73325302])

In [45]:
np.log(pred)

array([-0.82098055, -3.5065579 , -0.597837  ])

In [46]:
np.sqrt(pred)

array([0.66332496, 0.17320508, 0.74161985])

In [47]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [48]:
result = pred >= 0.5
result

array([False, False,  True])

In [49]:
np.random.seed(2)

In [50]:
pred1 = np.random.rand(3).round(2)
pred1

array([0.44, 0.03, 0.55])

In [51]:
pred2 = np.random.rand(3).round(2)
pred2

array([0.44, 0.42, 0.33])

In [52]:
pred1 >= pred2

array([ True, False,  True])

In [53]:
np.random.seed(2)

In [54]:
pred1 = np.random.rand(3) >= 0.3
pred1

array([ True, False,  True])

In [55]:
pred2 = np.random.rand(3) >= 0.4
pred2

array([ True,  True, False])

In [56]:
pred1 & pred2

array([ True, False, False])

In [57]:
pred1 | pred2

array([ True,  True,  True])

In [58]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred_sum = pred.sum()
pred

array([0.44, 0.03, 0.55])

In [59]:
pred_sum

1.02

In [60]:
print('min = %.2f' % pred.min())
print('mean = %.2f' % pred.mean())
print('max = %.2f' % pred.max())
print('std = %.2f' % pred.std())

min = 0.03
mean = 0.34
max = 0.55
std = 0.22


In [61]:
np.random.seed(2)
matrix = np.random.rand(4, 3).round(2)
matrix

array([[0.44, 0.03, 0.55],
       [0.44, 0.42, 0.33],
       [0.2 , 0.62, 0.3 ],
       [0.27, 0.62, 0.53]])

In [62]:
matrix.max()

0.62

In [63]:
matrix.max(axis=1)

array([0.55, 0.44, 0.62, 0.62])

In [64]:
matrix.max(axis=0)

array([0.44, 0.62, 0.55])

In [65]:
matrix.sum(axis=1)

array([1.02, 1.19, 1.12, 1.42])

In [66]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [67]:
np.sort(pred)

array([0.03, 0.44, 0.44, 0.55])

In [68]:
pred

array([0.44, 0.03, 0.55, 0.44])

In [69]:
pred.sort()

In [70]:
pred

array([0.03, 0.44, 0.44, 0.55])

In [71]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [72]:
idx = pred.argsort()

In [73]:
idx

array([1, 0, 3, 2], dtype=int64)

In [74]:
pred[idx]

array([0.03, 0.44, 0.44, 0.55])

In [75]:
rng = np.arange(12)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
rng.shape

(12,)

In [77]:
rng.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [78]:
rng.reshape(4, 3, order='F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [79]:
rng.reshape(4, 4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [80]:
vec = np.arange(3)
vec

array([0, 1, 2])

In [81]:
mat = np.arange(6).reshape(3, 2)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [82]:
np.concatenate([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [83]:
np.hstack([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [84]:
np.hstack([mat, mat])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [85]:
np.concatenate([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [86]:
np.column_stack([vec, mat])

array([[0, 0, 1],
       [1, 2, 3],
       [2, 4, 5]])

In [87]:
np.column_stack([vec, vec])

array([[0, 0],
       [1, 1],
       [2, 2]])

In [88]:
np.vstack([vec, vec])

array([[0, 1, 2],
       [0, 1, 2]])

In [89]:
np.vstack([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [90]:
mat.T

array([[0, 2, 4],
       [1, 3, 5]])

In [91]:
np.vstack([vec, mat.T])

array([[0, 1, 2],
       [0, 2, 4],
       [1, 3, 5]])

In [92]:
mat = np.arange(15).reshape(5, 3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [93]:
mat[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [95]:
mat[:, :2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [96]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [97]:
mat[[3, 0, 1]]

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [98]:
mat[:, 0] % 2 == 1

array([False,  True, False,  True, False])

In [99]:
u = np.array([0, 1, 2])
v = np.array([1, 2, 3])

u.dot(v)

8

In [100]:
X = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [101]:
X.dot(u)

array([5, 8, 9])

In [102]:
U = np.array([
    [4, 5, 6],
    [5, 6, 7],
    [6, 7, 8]
])

In [103]:
X.dot(U)

array([[17, 20, 23],
       [32, 38, 44],
       [41, 49, 57]])

In [104]:
A = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [105]:
Ainv = np.linalg.inv(A)
Ainv

array([[-3.,  3., -1.],
       [ 3., -4.,  2.],
       [-1.,  2., -1.]])

In [106]:
A.dot(Ainv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [107]:
B = np.array([
    [0, 1, 1],
    [1, 2, 3],
    [2, 3, 5]
])

np.linalg.inv(B)

LinAlgError: Singular matrix

In [108]:
b = np.array([1, 2, 3])

In [109]:
x = np.linalg.solve(A, b)
x

array([0., 1., 0.])

In [110]:
A.dot(x)

array([1., 2., 3.])